project: 
  type: website
  
website: 
  page-navigation: true
  title: "Communicate Research Effectively with R" 
  site-url: "https://drarunmitra.github.io/communicating-research-workshop" 
  repo-url: https://github.com/drarunmitra/communicating-research-workshop 
  
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By SCTIMST, 2024"
    
  sidebar:
    logo: "images/CommRes_Hex.png"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://quarto.org
        text: "Quarto.org"
      - icon: github
        href: https://github.com/drarunmitra/communicating-research-workshop
        text: "Getting Started with Quarto" 

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome
      - section: foundations/index.qmd
        contents: 
          - foundations/chap_rep_research.qmd
          - foundations/chap_intro_r.qmd
          - foundations/chap_meet_quarto.qmd 
      - chap_first_document.qmd
      - chap_first_article.qmd
      - chap_adding_more.qmd


format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
execute:
  cache: true